### ISSUE TITLE
Error cocoapod Swift 3/4

### ISSUE THREAD

**Issue by mihailsalari** [michalrentka/MaterialTabBar#1]
![screen shot 2017-10-21 at 4 34 40 pm](https://user-images.githubusercontent.com/23311250/31852291-ce4c5e14-b67d-11e7-81d2-5828637556af.png)

**Comment by michalrentka** [comment]
Hi @mihailsalari,
`MaterialTabBar` was programmed in Swift 4 and you're probably trying to compile it using Swift 3, hence those errors. If you compile it using Swift version 4, you should be fine.

If you're still using Swift 3 in your project, you can set to compile this pod using Swift 4. Try adding this to your `Podfile`:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'MaterialTabBar'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```
